### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by InTheCloudDan** [TomasTomecek/ansible-bender#52]
I configured a docker container to install the dependencies and when I go to run ansible-bender inside the container I'm getting:
```
sh-4.2# ansible-bender --python-interpreter /usr/bin/python3
Traceback (most recent call last):
  File "/usr/bin/ansible-bender", line 7, in <module>
    from ansible_bender.cli import main
  File "/usr/lib/python3.4/site-packages/ansible_bender/cli.py", line 12, in <module>
    from ansible_bender.api import Application
  File "/usr/lib/python3.4/site-packages/ansible_bender/api.py", line 7, in <module>
    from ansible_bender.builder import get_builder
  File "/usr/lib/python3.4/site-packages/ansible_bender/builder.py", line 6, in <module>
    from ansible_bender.builders.buildah_builder import BuildahBuilder
  File "/usr/lib/python3.4/site-packages/ansible_bender/builders/buildah_builder.py", line 5, in <module>
    from ansible_bender.builders.base import Builder
  File "/usr/lib/python3.4/site-packages/ansible_bender/builders/base.py", line 71
    return f"layer_id={self.layer_id} cached={self.cached}"
                                                          ^
SyntaxError: invalid syntax
```

It's a `centos7:latest` container with the Dockerfile that just installs the necessary packages, unless I missed one somewhere.

**Comment by InTheCloudDan** [comment]
installed python 3.6 and that resolved it.

**Comment by TomasTomecek** [comment]
Hi! Thanks for taking time to open the issue.

Please let me know whether bender should explicitly tell that it's a python 3 only project -- I understand it can be a bit confusing.
